import type { Metadata } from "next";
import LayoutClient from "./layout.client";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ConvexAuthNextjsServerProvider>
			<html lang="en">
				<body>
					<LayoutClient>{children}</LayoutClient>
				</body>
			</html>
		</ConvexAuthNextjsServerProvider>
	);
}
