import type { Metadata } from "next";
import LayoutClient from "./layout.client";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import LayoutServer from "./layout.server";
import { Roboto } from "next/font/google";

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-roboto",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ConvexAuthNextjsServerProvider>
			<html lang="en" className={roboto.variable}>
				<body>
					<LayoutServer>
						<LayoutClient>{children}</LayoutClient>
					</LayoutServer>
				</body>
			</html>
		</ConvexAuthNextjsServerProvider>
	);
}
